### ISSUE TITLE
Framebuffer device for `cairo-fb` is hardcoded to `/dev/fb0`.

### ISSUE THREAD

**Issue by jimsynz** [ScenicFramework/scenic_driver_local#68]
Hi there.

I have a small SPI connected display that I have working using the Linux `fbtft` driver.  I've been struggling to get Scenic to work, and finally managed to get it working by using the `cairo-fb` driver from `main`. Unfortunately the driver has the framebuffer device hardcoded to `/dev/fb0` and my display is registered as `/dev/fb1`.  I worked around it by symlinking `/dev/fb0` to `/dev/fb1` and have been rewarded with my scene displaying.  Pretty exciting.

Is there any way we can make this a configurable option?

Thanks!

**Comment by crertel** [comment]
Looks like we pass in args [here](https://github.com/ScenicFramework/scenic_driver_local/blob/789d5fd7f9fcad34170c872572f8c495157890be/lib/driver.ex#L232-L240) and then add them to the global options [here](https://github.com/ScenicFramework/scenic_driver_local/blob/789d5fd7f9fcad34170c872572f8c495157890be/c_src/main.c#L38-L48). 

That options struct is defined [here](https://github.com/ScenicFramework/scenic_driver_local/blob/789d5fd7f9fcad34170c872572f8c495157890be/c_src/scenic/scenic_types.h#L61-L73) and then we set the framebuffer name [here](https://github.com/ScenicFramework/scenic_driver_local/blob/789d5fd7f9fcad34170c872572f8c495157890be/c_src/device/cairo/cairo_fb.c#L103).

I bet we could just pass this in as another command-line argument, set it on that global struct, load from the global opts struct instead of a c-file constant, and then bob's your uncle.
